//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApplication1.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CampaignData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CampaignData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestWebApplication1.Tests.Resources.CampaignData", typeof(CampaignData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Campaigns&gt;
        ///  &lt;dbo.Campaign&gt;
        ///    &lt;Id&gt;51902&lt;/Id&gt;
        ///    &lt;CampaignTypeId&gt;49751&lt;/CampaignTypeId&gt;
        ///    &lt;PartnerId&gt;186&lt;/PartnerId&gt;
        ///    &lt;Name&gt;Create Angebot (SN/DYN) POS&lt;/Name&gt;
        ///    &lt;Active&gt;0&lt;/Active&gt;
        ///    &lt;ValidFrom&gt;2021-04-01T00:00:00&lt;/ValidFrom&gt;
        ///    &lt;ValidTill&gt;2021-04-30T00:00:00&lt;/ValidTill&gt;
        ///    &lt;DisplayFrom&gt;2021-04-01T00:00:00&lt;/DisplayFrom&gt;
        ///    &lt;DisplayTill&gt;2021-04-30T00:00:00&lt;/DisplayTill&gt;
        ///    &lt;DiscountType&gt;&lt;/DiscountType&gt;
        ///    &lt;DiscountValue&gt;&lt;/DiscountValue&gt;
        ///    &lt;Priority&gt;100&lt;/Priority&gt;
        ///    &lt;OrdinalP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CampaignDataXml {
            get {
                return ResourceManager.GetString("CampaignDataXml", resourceCulture);
            }
        }
    }
}
